// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7mzV5w9Lahr6YESN-LL1L6P9FXqpmeXA',
    appId: '1:794380091387:web:15bafc789e10719524d55e',
    messagingSenderId: '794380091387',
    projectId: 'chat-app-dc90c',
    authDomain: 'chat-app-dc90c.firebaseapp.com',
    storageBucket: 'chat-app-dc90c.appspot.com',
    measurementId: 'G-PF1N5WWJC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI6SQmxV-dP7V4GFmRssD_xjlmuVHw-nw',
    appId: '1:794380091387:android:67d7c47b5a64d31f24d55e',
    messagingSenderId: '794380091387',
    projectId: 'chat-app-dc90c',
    storageBucket: 'chat-app-dc90c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaQuw6k6_mFj51tIFYHg_N75pH_o_sdng',
    appId: '1:794380091387:ios:bec1fc24264c351324d55e',
    messagingSenderId: '794380091387',
    projectId: 'chat-app-dc90c',
    storageBucket: 'chat-app-dc90c.appspot.com',
    iosClientId: '794380091387-98scdcmh80n56huno8ngvht2342euomu.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaQuw6k6_mFj51tIFYHg_N75pH_o_sdng',
    appId: '1:794380091387:ios:bec1fc24264c351324d55e',
    messagingSenderId: '794380091387',
    projectId: 'chat-app-dc90c',
    storageBucket: 'chat-app-dc90c.appspot.com',
    iosClientId: '794380091387-98scdcmh80n56huno8ngvht2342euomu.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
